# Deployment for Ktor application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdoc-deployment
  namespace: kdoc-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kdoc
  template:
    metadata:
      labels:
        app: kdoc
    spec:
      containers:
        - name: kdoc
          image: kdoc-image:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 5005
          env:
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: KDOC_KTOR_SECURITY_SSL_KEY_STORE
              value: "/app/keystore.p12"
